trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Set up Python environment
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Change this to your desired Python version
    addToPath: true

# Step 2: Install dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# Step 3: Run tests
- script: |
    pytest
  displayName: 'Run tests'

# Step 4: Publish build artifacts (optional)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: drop
  condition: succeededOrFailed()
